my:
  greeting: Hello, world!
  list:
    values: One, Two, Three

db:
  connection: connection-string-from-config-server
  host: 127.0.0.1
  port: 3306

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  profiles:
    active: test
