spring:
  application:
    name: currency-conversion-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8100
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"