spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:\\D:\\Anjan\\Spring Boot App\\Currency Exchange and Conversion\\configrepo

server:
  port: 8888