spring.application.name: spring-boot-config
my:
  greeting: Hello, world!
  list:
    values: One, Two, Three

db:
  connection: test-connection-string
  host: 127.0.0.1
  port: 3308

management:
  endpoints:
    web:
      exposure:
        include: "*"
